#!/usr/bin/env python

import glob
import re
import sys

pngFiles = []
export = []

extensionsToCheck = ('.png', '.jpg', '.svg')

extensionName = 'js'

if(len(sys.argv) == 2):
  extensionName =  sys.argv[1]

for file in glob.glob("*"):
  if not re.search("@", file) :
    if file.endswith(extensionsToCheck):
      name = re.split('(\.png$|\.jpg$|\.svg$)', file)[0]
      title = "export { default as " + name + " } from " + "'./" + file + "';"
      pngFiles.append(title)

importText = "\n".join(str(x) for x in pngFiles)
f= open("index."+extensionName,"w+")
f.write(importText)
