#!/usr/bin/env python

import glob
import re

pngFiles = []
export = []

extensionsToCheck = ('.png', '.jpg', '.svg')

for file in glob.glob("*"):
  if not re.search("@", file) :
    if file.endswith(extensionsToCheck):
      name = re.split('(\.png$|\.jpg$|\.svg$)', file)[0]
      title = "export { default as " + name + " } from " + "'./" + file + "';"
      pngFiles.append(title)

importText = "\n".join(str(x) for x in pngFiles)
f= open("index.js","w+")
f.write(importText)
