#!/bin/bash

# sysinfo_page - A script to produce an html file
title="System Information for"

cat << _EOF_
<html>
<head>
    <title>
      $title
    </title>
</head>

<body>
    Your page content goes here.
</body>
</html>
_EOF_