#!/usr/bin/env python

import glob
import re

componentFiles = []
export = []
for file in glob.glob("*.js"):
  name = re.split(".js", file)[0]
  if str(name)[0].isupper():
    title = "import " + name + " from " + "'./" + name + "';"
    componentFiles.append(title)
    export.append(name)

importText = "\n".join(str(x) for x in componentFiles)
exportText = ",\n  ".join(str(x) for x in export)
f= open("index.js","w+")
f.write(importText)
f.write('\n\n')
f.write('export {\n  ')
f.write(exportText)
f.write(',\n};\n')
