#!/usr/bin/env bash

case "$1" in
  "b")
    addCMD=$(eval "git add -A")
    # commitCMD="git commit -m'${@:3}'"
    # # $(eval "git commit -m \'something\'")
    # echo $commitCMD
    # $(eval $commitCMD)
    git commit -m "something"
    ;;
  *)
    echo 'no branch'
    ;;
esac